Endpoint fixes
AzureAD/SCIMReferenceCode pull request #30
Opened 2020-05-28 22:53 UTC by Ryanmeakins

The provider base class does not return any values for resource types or schemas.
In order to increase the usefulness of the sample provider sample values have been added to the returned collection for Types and Schemas.

2020-06-03 09:09 UTC, Adam-GitHubq commented on Microsoft.SCIM.WebHostSample/Resources/SampleTypeScheme.cs
> +        public static TypeScheme UserTypeSceme
UserTypeScheme

2020-08-10 10:17 UTC, mllab-nl commented
Good PR @Ryanmeakins 
Any reason it is not being merged ?

2021-05-06 15:06 UTC, peteretelej requested changes

2021-05-06 15:13 UTC, charitymarani commented on Microsoft.SCIM.WebHostSample/Resources/SampleResourceTypes.cs
> +using System.Threading.Tasks;
Working on the changes

2021-05-06 15:14 UTC, peteretelej commented on Microsoft.SCIM.WebHostSample/Provider/InMemoryProvider.cs
> +        }
since it returns value, this can be expression body `ResourceTypes => InMemoryProvider.Types.Value;`

2021-05-11 14:18 UTC, peteretelej approved these changes
Approving to unblock, since payload matches spec. I think this endpoint also requires Auth (at the moment accessible without auth).

Also, the /Schemas endpoint should list all attributes *supported* by the endpoint ( see RFC [here](https://datatracker.ietf.org/doc/html/rfc7644#sectin-4))
>  An HTTP GET to the endpoint "/Schemas" SHALL return all supported schemas in ListResponse format 

A few attributes are missing from those supported by this scim app. For example for User resource: `nickName`, `timezone`, `roles`, and some subattributes eg in `name`.

2021-07-20 19:48 UTC, blairno commented
The latest version of this branch returns an empty "schemas" array when creating a new user.
For example, using the following payload to POST a new User resource:
`{
    "UserName": "UserName222",
    "Active": true,
    "DisplayName": "lennay",
    "schemas": [
        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User",
        "urn:ietf:params:scim:schemas:core:2.0:User"
    ],
  "externalId": "${__UUID}",
    "name": {
        "formatted": "Adrew Ryan",
        "familyName": "Ryan",
        "givenName": "Andrew"
    },
    "emails": [
        {
            "Primary": true,
            "type": "work",
            "value": "testing@bob2.com"
        },
        {
            "Primary": false,
            "type": "home",
            "value": "testinghome@bob3.com"
        }
    ],
    "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": {
    		"Department": "bob",
    		"Manager" : { "Value": "SuzzyQ" }
    }
}`

The returned response is as follows (the "schemas" attribute is an empty array).
`{
    "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": {
        "manager": {
            "value": "SuzzyQ"
        },
        "department": "bob"
    },
    "active": true,
    "displayName": "lennay",
    "emails": [
        {
            "type": "work",
            "primary": true,
            "value": "testing@bob2.com"
        },
        {
            "type": "home",
            "primary": false,
            "value": "testinghome@bob3.com"
        }
    ],
    "meta": {
        "resourceType": "User"
    },
    "name": {
        "formatted": "Adrew Ryan",
        "familyName": "Ryan",
        "givenName": "Andrew"
    },
    "userName": "UserName222",
    "externalId": "${__UUID}",
    "id": "13b49587-4efd-46ad-af94-ee9f54874fda",
    "schemas": []
}`

This does not happen with the Master branch, which correctly returns the expected array of "schemas".

2021-07-27 13:19 UTC, charitymarani commented
> The latest version of this branch returns an empty "schemas" array when creating a new user.
> For example, using the following payload to POST a new User resource:
> `{ "UserName": "UserName222", "Active": true, "DisplayName": "lennay", "schemas": [ "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User", "urn:ietf:params:scim:schemas:core:2.0:User" ], "externalId": "${__UUID}", "name": { "formatted": "Adrew Ryan", "familyName": "Ryan", "givenName": "Andrew" }, "emails": [ { "Primary": true, "type": "work", "value": "testing@bob2.com" }, { "Primary": false, "type": "home", "value": "testinghome@bob3.com" } ], "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": { "Department": "bob", "Manager" : { "Value": "SuzzyQ" } } }`
> 
> The returned response is as follows (the "schemas" attribute is an empty array).
> `{ "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": { "manager": { "value": "SuzzyQ" }, "department": "bob" }, "active": true, "displayName": "lennay", "emails": [ { "type": "work", "primary": true, "value": "testing@bob2.com" }, { "type": "home", "primary": false, "value": "testinghome@bob3.com" } ], "meta": { "resourceType": "User" }, "name": { "formatted": "Adrew Ryan", "familyName": "Ryan", "givenName": "Andrew" }, "userName": "UserName222", "externalId": "${__UUID}", "id": "13b49587-4efd-46ad-af94-ee9f54874fda", "schemas": [] }`
> 
> This does not happen with the Master branch, which correctly returns the expected array of "schemas".
> 
> Reversing the 2 line change in "Microsoft.SystemForCrossDomainIdentityManagement/Schemas/Schematized.cs" seems to fix that issue on my machine, but I am not sure what else that might impact or what the original purpose of that change was.
> 
> I think the issue is that in the change the "IReadOnlyCollection Schemas" field is being decorated as the DataMember named "Schemas" which returns an empty array when it is serialized into json since I don't think "IReadOnlyCollection" supports serialization.
> Prior to the change, the "List schemas" field was decorated as the DataMember named "Schemas" which is able to be successfully serialized.
> ^^^ @charitymarani

@blairno I just confirmed the issue. Thank you for noticing.

2021-08-03 07:20 UTC, michaelkaboro approved these changes

2021-08-03 08:10 UTC, owinoakelo commented
#sign-off

2021-08-03 14:38 UTC, merged